-- GENERATED by run_calibration_protocol_vkr.lua. Do not hand-edit.
--
-- The protocol's decisions, and fingerprints of the inputs they were made
-- from. export_production_models.lua reads this and refuses to export if any
-- fingerprint no longer matches the file it describes.
--
-- Regenerate with:  lua dev/calibration/run_protocol_offline.lua

CALIBRATION_MANIFEST = {
    schema   = 2,
    complete = true,
    inputs = {
        csv_hash      = "07aae114239c9dbb",
        csv_bytes     = 1140165,
        csv_rows      = 2101,
        protocol_hash = "c60fe760e765a315",
        factors_hash  = "73d526ddb35359fe",
        factors_n     = 114,
        lua           = "Lua 5.4",
    },
    protocol = {
        n_repeats     = 10,
        nfold         = 5,
        inner_fold    = 3,
        seed          = 20260812,
        usable_floor  = 0.9000,
        miss_ceiling  = 0.0500,
        rho_floor     = 0.7000,
    },
    selections = {
        {
            inst = "guitar", candidate = "full@attacks", scale = "log(rank)",
            n_features = 21, n_target = 327, n_aux = 60, n_weird = 0,
            usable_mean = 0.942202, usable_lower = 0.917122, miss_upper = 0.013591,
            rho_mean = 0.861800, rho_lo_split = 0.858775, rho_hi_split = 0.866117,
            rho_lower = 0.830323,
            gate_passed = true,
        },
        {
            inst = "bass", candidate = "baseline+entropy", scale = "log(rank)",
            n_features = 3, n_target = 330, n_aux = 60, n_weird = 0,
            usable_mean = 0.941818, usable_lower = 0.916810, miss_upper = 0.013468,
            rho_mean = 0.801849, rho_lo_split = 0.798896, rho_hi_split = 0.804071,
            rho_lower = 0.745812,
            gate_passed = true,
        },
        {
            inst = "drum", candidate = "full_drum@noroll", scale = "log(rank)",
            n_features = 26, n_target = 328, n_aux = 60, n_weird = 0,
            usable_mean = 0.963415, usable_lower = 0.942222, miss_upper = 0.013550,
            rho_mean = 0.893795, rho_lo_split = 0.891052, rho_hi_split = 0.896386,
            rho_lower = 0.868691,
            gate_passed = true,
        },
        {
            inst = "vocals", candidate = "parts+tess+move@parts_step3", scale = "log(rank)",
            n_features = 12, n_target = 328, n_aux = 60, n_weird = 0,
            usable_mean = 0.886280, usable_lower = 0.854229, miss_upper = 0.042768,
            rho_mean = 0.674024, rho_lo_split = 0.665678, rho_hi_split = 0.684745,
            rho_lower = 0.606371,
            gate_passed = false,
        },
        {
            inst = "keys", candidate = "primary+ent_rel+complex@attacks-chord", scale = "rank",
            n_features = 7, n_target = 266, n_aux = 0, n_weird = 0,
            usable_mean = 0.929699, usable_lower = 0.899354, miss_upper = 0.010802,
            rho_mean = 0.877668, rho_lo_split = 0.873604, rho_hi_split = 0.881629,
            rho_lower = 0.837109,
            gate_passed = false,
        },
        {
            inst = "real_keys", candidate = "primary+ent_rel@attacks", scale = "rank",
            n_features = 7, n_target = 266, n_aux = 0, n_weird = 0,
            usable_mean = 0.893985, usable_lower = 0.858869, miss_upper = 0.020207,
            rho_mean = 0.860907, rho_lo_split = 0.858350, rho_hi_split = 0.863105,
            rho_lower = 0.823832,
            gate_passed = false,
        },
    },
}
